-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.users
(
    id bigserial NOT NULL,
    email text,
    nickname text NOT NULL,
    password_hash text NOT NULL,
    avatar_storage_key text,
    bio text,
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    is_admin boolean,
    PRIMARY KEY (id),
    CONSTRAINT unique_nickname UNIQUE (nickname)
);

COMMENT ON TABLE public.users
    IS 'Таблица пользователей';

CREATE TABLE IF NOT EXISTS public.tracks
(
    id bigserial NOT NULL,
    uploader_user_id bigint NOT NULL,
    title text NOT NULL DEFAULT 'Untitled',
    artists text[],
    audio_storage_key text,
    cover_storage_key text,
    hash text,
    duration_ms integer,
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    PRIMARY KEY (id)
);

COMMENT ON TABLE public.tracks
    IS 'Таблица треков';

CREATE TABLE IF NOT EXISTS public.albums
(
    id bigserial NOT NULL,
    user_id bigint NOT NULL,
    title text,
    is_public boolean,
    cover_storage_key text,
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    PRIMARY KEY (id)
);

COMMENT ON TABLE public.albums
    IS 'Таблица хранения альбомов';

CREATE TABLE IF NOT EXISTS public.playlists
(
    id bigserial NOT NULL,
    user_id bigint NOT NULL,
    title text,
    is_public boolean,
    cover_storage_key text,
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    PRIMARY KEY (id)
);

COMMENT ON TABLE public.playlists
    IS 'Таблица плейлистов';

CREATE TABLE IF NOT EXISTS public.thoughts
(
    id bigserial NOT NULL,
    author_user_id bigint NOT NULL,
    body_text text,
    attachment_type integer,
    attachment_track_id bigint,
    attachment_playlist_id bigint,
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    PRIMARY KEY (id)
);

COMMENT ON TABLE public.thoughts
    IS 'Таблица мыслей пользователя (система твитер сообщений)';

CREATE TABLE IF NOT EXISTS public.comments
(
    id bigserial NOT NULL,
    thought_id bigint NOT NULL,
    author_user_id bigint NOT NULL,
    body_text text,
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    PRIMARY KEY (id)
);

COMMENT ON TABLE public.comments
    IS 'Таблица комментариев к мыслям';

CREATE TABLE IF NOT EXISTS public.colisten_sessions
(
    id bigserial NOT NULL,
    host_user_id bigint NOT NULL,
    title text,
    visibility integer,
    current_track_id bigint,
    position_ms integer,
    is_playing boolean,
    shuffle_enabled boolean,
    repeat_mode boolean,
    control_pause_host_only boolean,
    control_seek_host_only boolean,
    control_shuffle_host_only boolean,
    control_repeat_host_only boolean,
    control_skip_host_only boolean,
    edit_queue_host_only boolean,
    PRIMARY KEY (id)
);

COMMENT ON TABLE public.colisten_sessions
    IS 'Таблица сессий совместного прослушивания';

CREATE TABLE IF NOT EXISTS public.colisten_session_queue_items
(
    session_id bigint NOT NULL,
    "position" integer NOT NULL,
    track_id bigint NOT NULL,
    PRIMARY KEY ("position", session_id)
);

COMMENT ON TABLE public.colisten_session_queue_items
    IS 'Таблица очереди прослушивания для комнаты совместного прослушивания';

CREATE TABLE IF NOT EXISTS public.user_playback_queue_items
(
    user_id bigint NOT NULL,
    "position" integer NOT NULL,
    track_id bigint NOT NULL,
    PRIMARY KEY (user_id, "position")
);

COMMENT ON TABLE public.user_playback_queue_items
    IS 'Таблица очереди прослушивания пользователя для синхронизации между устройствами';

CREATE TABLE IF NOT EXISTS public.invite_keys
(
    id bigserial NOT NULL,
    key_code text NOT NULL,
    creator_user_id bigint NOT NULL,
    created_at timestamp with time zone,
    revoked_at timestamp with time zone,
    notes text,
    PRIMARY KEY (id),
    CONSTRAINT unique_key_code UNIQUE (key_code),
    CONSTRAINT unique_creator_user_id UNIQUE (creator_user_id)
);

COMMENT ON TABLE public.invite_keys
    IS 'Таблица созданных пригласительных ключей';

CREATE TABLE IF NOT EXISTS public.listen_events
(
    id bigserial NOT NULL,
    user_id bigint NOT NULL,
    track_id bigint NOT NULL,
    started_at timestamp with time zone,
    ended_at timestamp with time zone,
    duration_played_ms integer,
    source_type integer,
    source_id bigint,
    PRIMARY KEY (id)
);

COMMENT ON TABLE public.listen_events
    IS 'Таблица истории прослушиваний';

CREATE TABLE IF NOT EXISTS public.notifications
(
    id bigserial NOT NULL,
    recipient_user_id bigint,
    actor_user_id bigint,
    type integer,
    entity_ref text,
    entity_id bigint,
    payload_json jsonb,
    read_at timestamp with time zone,
    created_at timestamp with time zone,
    PRIMARY KEY (id)
);

COMMENT ON TABLE public.notifications
    IS 'Таблица уведомлений';

CREATE TABLE IF NOT EXISTS public.friend_requests
(
    from_user_id bigint NOT NULL,
    to_user_id bigint NOT NULL,
    status text DEFAULT 'pending',
    created_at timestamp with time zone,
    responded_at timestamp with time zone,
    PRIMARY KEY (from_user_id, to_user_id)
);

COMMENT ON TABLE public.friend_requests
    IS 'Таблица связей между пользователями (заявки в друзья)';

CREATE TABLE IF NOT EXISTS public.friendships
(
    user_low bigint NOT NULL,
    user_high bigint NOT NULL,
    created_at timestamp with time zone,
    PRIMARY KEY (user_low, user_high),
    CONSTRAINT friendships_order_chk CHECK (user_low < user_high)
);

COMMENT ON TABLE public.friendships
    IS 'Принятая дружба: одна строка на пару (user_low < user_high)';

CREATE TABLE IF NOT EXISTS public.user_now_playing
(
    user_id bigint NOT NULL,
    track_id bigint,
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    PRIMARY KEY (user_id),
    CONSTRAINT user_now_playing_user_fk FOREIGN KEY (user_id)
        REFERENCES public.users (id) ON DELETE CASCADE,
    CONSTRAINT user_now_playing_track_fk FOREIGN KEY (track_id)
        REFERENCES public.tracks (id) ON DELETE SET NULL
);

COMMENT ON TABLE public.user_now_playing
    IS 'Последний трек, который пользователь отметил как «сейчас слушает»';

CREATE TABLE IF NOT EXISTS public.track_likes
(
    user_id bigint NOT NULL,
    track_id bigint NOT NULL,
    PRIMARY KEY (user_id, track_id)
);

CREATE TABLE IF NOT EXISTS public.playlist_likes
(
    playlist_id bigint NOT NULL,
    user_id bigint NOT NULL,
    PRIMARY KEY (playlist_id, user_id)
);

CREATE TABLE IF NOT EXISTS public.thought_likes
(
    thought_id bigint NOT NULL,
    user_id bigint NOT NULL,
    PRIMARY KEY (thought_id, user_id)
);

CREATE TABLE IF NOT EXISTS public.album_tracks
(
    track_id bigint NOT NULL,
    album_id bigint NOT NULL,
    "position" integer NOT NULL,
    PRIMARY KEY (album_id, "position"),
    CONSTRAINT unique_album_track_id UNIQUE (track_id, album_id)
);

CREATE TABLE IF NOT EXISTS public.colisten_session_participants
(
    colisten_session_id bigint NOT NULL,
    user_id bigint NOT NULL,
    PRIMARY KEY (colisten_session_id, user_id)
);

CREATE TABLE IF NOT EXISTS public.auth_sessions
(
    id bigserial NOT NULL,
    user_id bigint NOT NULL,
    token_hash text NOT NULL,
    ip_address text,
    device_label text,
    PRIMARY KEY (id),
    CONSTRAINT unique_token_hash UNIQUE (token_hash)
);

CREATE TABLE IF NOT EXISTS public.playlist_tracks
(
    track_id bigint NOT NULL,
    playlist_id bigint NOT NULL,
    "position" integer NOT NULL,
    PRIMARY KEY (playlist_id, "position")
);

-- Жанры (справочник; slug совпадает с клиентом studioGenreIds)
CREATE TABLE IF NOT EXISTS public.genres
(
    id bigserial NOT NULL,
    slug text NOT NULL,
    display_name text NOT NULL,
    parent_genre_id bigint,
    sort_order integer NOT NULL DEFAULT 0,
    created_at timestamp with time zone,
    PRIMARY KEY (id),
    CONSTRAINT genres_slug_unique UNIQUE (slug),
    CONSTRAINT genres_parent_fk FOREIGN KEY (parent_genre_id)
        REFERENCES public.genres (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE SET NULL
);

COMMENT ON TABLE public.genres
    IS 'Справочник жанров для тегирования и рекомендаций';

-- Теги жанров у трека (веса независимы, по умолчанию 1.0)
CREATE TABLE IF NOT EXISTS public.track_genres
(
    track_id bigint NOT NULL,
    genre_id bigint NOT NULL,
    weight double precision NOT NULL DEFAULT 1.0,
    source text NOT NULL DEFAULT 'uploader',
    PRIMARY KEY (track_id, genre_id),
    CONSTRAINT track_genres_track_fk FOREIGN KEY (track_id)
        REFERENCES public.tracks (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE,
    CONSTRAINT track_genres_genre_fk FOREIGN KEY (genre_id)
        REFERENCES public.genres (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE,
    CONSTRAINT track_genres_weight_chk CHECK (weight >= 0::double precision AND weight <= 100::double precision)
);

COMMENT ON TABLE public.track_genres
    IS 'Жанры трека с весами (рекомендации, фильтры)';

CREATE TABLE IF NOT EXISTS public.album_genres
(
    album_id bigint NOT NULL,
    genre_id bigint NOT NULL,
    weight double precision NOT NULL DEFAULT 1.0,
    source text NOT NULL DEFAULT 'owner',
    PRIMARY KEY (album_id, genre_id),
    CONSTRAINT album_genres_album_fk FOREIGN KEY (album_id)
        REFERENCES public.albums (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE,
    CONSTRAINT album_genres_genre_fk FOREIGN KEY (genre_id)
        REFERENCES public.genres (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE,
    CONSTRAINT album_genres_weight_chk CHECK (weight >= 0::double precision AND weight <= 100::double precision)
);

COMMENT ON TABLE public.album_genres
    IS 'Жанры альбома (метаданные подборок)';

-- Явные предпочтения пользователя по жанрам (влияют на GET /recommendations/tracks)
CREATE TABLE IF NOT EXISTS public.user_genre_preferences
(
    user_id bigint NOT NULL,
    genre_id bigint NOT NULL,
    weight double precision NOT NULL DEFAULT 1.0,
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    PRIMARY KEY (user_id, genre_id),
    CONSTRAINT user_genre_pref_user_fk FOREIGN KEY (user_id)
        REFERENCES public.users (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE,
    CONSTRAINT user_genre_pref_genre_fk FOREIGN KEY (genre_id)
        REFERENCES public.genres (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE,
    CONSTRAINT user_genre_pref_weight_chk CHECK (weight >= 0::double precision AND weight <= 100::double precision)
);

COMMENT ON TABLE public.user_genre_preferences
    IS 'Пользовательские веса жанров для персонализации';

-- Учёт показов и реакций на рекомендации (полиморфный target без FK на target_id)
CREATE TABLE IF NOT EXISTS public.recommendation_events
(
    id bigserial NOT NULL,
    user_id bigint NOT NULL,
    surface text NOT NULL,
    target_type text NOT NULL,
    target_id bigint NOT NULL,
    interaction text NOT NULL,
    score_present double precision,
    meta text,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    PRIMARY KEY (id),
    CONSTRAINT recommendation_events_user_fk FOREIGN KEY (user_id)
        REFERENCES public.users (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
);

COMMENT ON TABLE public.recommendation_events
    IS 'События рекомендаций: impression, click, dismiss, play_start';

CREATE INDEX IF NOT EXISTS idx_recommendation_events_user_created
    ON public.recommendation_events (user_id, created_at DESC);

ALTER TABLE IF EXISTS public.tracks
    ADD CONSTRAINT track_uploader_user_id_constraint FOREIGN KEY (uploader_user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.albums
    ADD CONSTRAINT album_owner_user_id_constraint FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.playlists
    ADD CONSTRAINT playlist_owner_constraint FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.thoughts
    ADD CONSTRAINT thought_author_user_id_constraint FOREIGN KEY (author_user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.comments
    ADD CONSTRAINT comments_thought_id_constraint FOREIGN KEY (thought_id)
    REFERENCES public.thoughts (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.comments
    ADD CONSTRAINT comments_author_user_id_constraint FOREIGN KEY (author_user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.colisten_sessions
    ADD CONSTRAINT colisten_host_user_id_constraint FOREIGN KEY (host_user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.colisten_sessions
    ADD CONSTRAINT colisten_current_track_id_constraint FOREIGN KEY (current_track_id)
    REFERENCES public.tracks (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.colisten_session_queue_items
    ADD CONSTRAINT colisten_session_queue_track_id_constraint FOREIGN KEY (track_id)
    REFERENCES public.tracks (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.colisten_session_queue_items
    ADD CONSTRAINT colisten_session_queue_session_id_constraint FOREIGN KEY (session_id)
    REFERENCES public.colisten_sessions (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.user_playback_queue_items
    ADD CONSTRAINT user_id_playback_user_constraint FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.user_playback_queue_items
    ADD CONSTRAINT track_id_playback_track_constraint FOREIGN KEY (track_id)
    REFERENCES public.tracks (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.invite_keys
    ADD CONSTRAINT invite_keys_constraint FOREIGN KEY (creator_user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.listen_events
    ADD CONSTRAINT listen_events_user_id_constraint FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.listen_events
    ADD CONSTRAINT listen_events_track_id_constraint FOREIGN KEY (track_id)
    REFERENCES public.tracks (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.notifications
    ADD CONSTRAINT recipient_user_id FOREIGN KEY (recipient_user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.notifications
    ADD CONSTRAINT actor_user_id FOREIGN KEY (actor_user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.friend_requests
    ADD CONSTRAINT friends_from_user_id_constraint FOREIGN KEY (from_user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.friend_requests
    ADD CONSTRAINT friends_to_user_id_constraint FOREIGN KEY (to_user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.friendships
    ADD CONSTRAINT friendships_user_low_fk FOREIGN KEY (user_low)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public.friendships
    ADD CONSTRAINT friendships_user_high_fk FOREIGN KEY (user_high)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public.track_likes
    ADD CONSTRAINT track_likes_user_id_constraint FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.track_likes
    ADD CONSTRAINT track_likes_track_id_constraint FOREIGN KEY (track_id)
    REFERENCES public.tracks (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.playlist_likes
    ADD CONSTRAINT playlist_likes_playlist_id_constraint FOREIGN KEY (playlist_id)
    REFERENCES public.playlists (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.playlist_likes
    ADD CONSTRAINT playlist_likes_user_id_constraint FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.thought_likes
    ADD CONSTRAINT thought_likes_thought_id_constraint FOREIGN KEY (thought_id)
    REFERENCES public.thoughts (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.thought_likes
    ADD CONSTRAINT thought_likes_user_id_constraint FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.album_tracks
    ADD CONSTRAINT album_tracks_track_id_constraint FOREIGN KEY (track_id)
    REFERENCES public.tracks (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.album_tracks
    ADD CONSTRAINT album_tracks_album_id_constraint FOREIGN KEY (album_id)
    REFERENCES public.albums (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.colisten_session_participants
    ADD CONSTRAINT colisten_session_user_id_constraint FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.colisten_session_participants
    ADD CONSTRAINT colisten_session_id_constraint FOREIGN KEY (colisten_session_id)
    REFERENCES public.colisten_sessions (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.auth_sessions
    ADD CONSTRAINT auth_sessions_constraint FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.playlist_tracks
    ADD CONSTRAINT playlist_tracks_playlist_id_constraint FOREIGN KEY (playlist_id)
    REFERENCES public.playlists (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.playlist_tracks
    ADD CONSTRAINT playlist_tracks_track_id_constraint FOREIGN KEY (track_id)
    REFERENCES public.tracks (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

-- Стартовый каталог жанров (совпадает с Flutter studioGenreIds)
INSERT INTO public.genres (slug, display_name, sort_order, created_at)
VALUES
    ('pop', 'Pop', 10, now()),
    ('rock', 'Rock', 20, now()),
    ('electronic', 'Electronic', 30, now()),
    ('hip_hop', 'Hip-Hop', 40, now()),
    ('rb', 'R&B', 50, now()),
    ('jazz', 'Jazz', 60, now()),
    ('classical', 'Classical', 70, now()),
    ('ambient', 'Ambient', 80, now()),
    ('lo_fi', 'Lo-Fi', 90, now()),
    ('metal', 'Metal', 100, now()),
    ('punk', 'Punk', 110, now()),
    ('indie', 'Indie', 120, now()),
    ('folk', 'Folk', 130, now()),
    ('country', 'Country', 140, now()),
    ('reggae', 'Reggae', 150, now()),
    ('drum_bass', 'Drum & Bass', 160, now()),
    ('house', 'House', 170, now()),
    ('techno', 'Techno', 180, now()),
    ('trance', 'Trance', 190, now()),
    ('dubstep', 'Dubstep', 200, now()),
    ('other', 'Other', 900, now())
ON CONFLICT (slug) DO NOTHING;

COMMIT;